### PR TITLE
Update README.md and move contributing information to NILDB

### PR DESCRIPTION
**Pull request by HactarCE**

### CODE REVIEW

**Comment by HactarCE** [comment]
Closing due to conflict; I'll open a new PR without the "Update NILDB" commit

**Comment by HactarCE** [comment]
Never mind. GitHub won't let me create a PR from a single revision, so you'll just have to deal with the conflict.. Worst case scenario, just delete NILDB and re-add it with `git submodule add`.

**Comment by porpoiseless** [comment]
Ok, I think I see what's going on. My submodules file points to my fork of NILDB. Best to keep each pair of repos synced separately unless there's a git command that takes care of it all automatically.

**Comment by HactarCE** [comment]
I don't think there's a way to do that without manually correcting the submodule origin whenever we merge back and forth. Can I just add you as a collaborator on HactarCE/NILDB?

**Comment by porpoiseless** [comment]
If you like, go ahead and add me as a collaborator. Until then, I guess I can include your version in my fork of the freedoc, and kind of zig-zag the PRs.

**Pull request merged**
